### ISSUE TITLE
【期望】支持api控制

### ISSUE THREAD

**Issue by Ikaros-521** [TopSea/Alive#1]
如题，比如通过api控制换模型 动作 等
期望 http协议实现api

**Comment by TopSea** [comment]
我也有这个想法，这样可以和 ai 或者其他软件联动，可玩性高一些。不过现在比较忙，应该要过一段时间了。

**Comment by Ikaros-521** [comment]
> 我也有这个想法，这样可以和 ai 或者其他软件联动，可玩性高一些。不过现在比较忙，应该要过一段时间了。

好好好

**Comment by TopSea** [comment]
> 我也有这个想法，这样可以和 ai 或者其他软件联动，可玩性高一些。不过现在比较忙，应该要过一段时间了。
搞错了，再打开一下。

**Comment by TopSea** [comment]
Alive 已加入 HTTP Server，下个版本发布就可以使用了，届时会添加 API 文档。
另外如果想添加 AI 功能，请参考这个项目 [AliveAi](https://github.com/TopSea/AliveAi) 。

**Comment by Ikaros-521** [comment]
> Alive 已加入 HTTP Server，下个版本发布就可以使用了，届时会添加 API 文档。
> 另外，如果想添加 AI 功能，请前往这个项目：[AliveAi](https://github.com/TopSea/AliveAi) 。

好好好
